version: '3.8'

services:
  thor:
    image: aidotnet/thor:latest
    ports:
      - 18080:8080
    build:
      context: .
      dockerfile: src/Thor.Service/Dockerfile
    container_name: thor
    volumes:
      - ./data:/data
      - ./Logs:/app/Logs
    environment:
      - TZ=Asia/Shanghai
