version: '3.8'

services:
  thor:
    image: aidotnet/thor:latest
    ports:
      - 18080:8080
    build:
      context: .
      dockerfile: src/Thor.Service/Dockerfile
    container_name: thor
    depends_on:
      - ai-rabbitmq
      - ai-redis
      - postgres
    volumes:
      - ./data:/data
      - ./Logs:/app/Logs
    environment:
      - TZ=Asia/Shanghai
      - DBType=postgresql # sqlite | [postgresql,pgsql] | [sqlserver,mssql] | mysql
      - ConnectionStrings:DefaultConnection=Host=ai-postgres;Port=5432;Database=aidotnet;Username=aidotnet;Password=aidotnet;Maximum Pool Size=1000
      - ConnectionStrings:LoggerConnection=Host=ai-postgres;Port=5432;Database=aidotnet-log;Username=aidotnet;Password=aidotnet;Maximum Pool Size=1000
      - CACHE_TYPE=Redis
      - CACHE_CONNECTION_STRING=ai-redis,retry=3,maxpoolsize=500,minpoolsize=300
      - RabbitMQ:ConnectionString=amqp://admin:admin@ai-rabbitmq:5672
      - OTEL_SERVICE_NAME=Thor
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - HttpClientPoolSize=8

  postgres:
    image: postgres:13
    container_name: ai-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aidotnet
      POSTGRES_PASSWORD: aidotnet
      POSTGRES_DB: aidotnet
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  ai-redis:
    image: redis
    container_name: ai-redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2
    container_name: aspire-dashboard
    ports:
      - "18888:18888"
    environment:
      - TZ=Asia/Shanghai
      - Dashboard:ApplicationName=Aspire


  ai-rabbitmq:
    image: rabbitmq:3-management
    container_name: ai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin