version: '3.8'

services:
  ai-dotnet-api-service:
    image: hejiale010426/thor:latest
    ports:
      - 18080:8080
    build:
      context: .
      dockerfile: src/Thor.Service/Dockerfile
    container_name: thor
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - DBType=sqlite # sqlite | [postgresql,pgsql] | [sqlserver,mssql] | mysql
      - ConnectionStrings:DefaultConnection=data source=/data/token.db
      - ConnectionStrings:LoggerConnection=data source=/data/logger.db
      - ASPNETCORE_PORTS=8080
      - RunMigrationsAtStartup=true